---
- name: Apply Ansible Automation Platform configuration from YAML definitions
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    absent_present: "{{ state | default('present') }}"

  pre_tasks:
    - name: Verify environment variable provided
      ansible.builtin.assert:
        that: 
          - env is defined
          - env == 'dev' or env == 'test' or env == 'prod'

    - name: Include vars for AAP 2.5 and newer
      ansible.builtin.include_vars:
        file: "../controller_vars/{{ env }}/secrets.yml"

    - name: Include Credential Type definitions
      ansible.builtin.include_vars:
        file: "../controller_vars/{{ env }}/controller_credential_types.yml"

  tasks:
    - name: 'Include task for managing credential types'
      when:
        - controller_credential_types is defined
        - controller_credential_types | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_credential_types
...
