---
- name: Playbook to configure Ansible Private Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    absent_present: "{{ state | default('present') }}"

  pre_tasks:
    - name: "Include variables from directory"
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/hub_vars/"
        extensions:
          - 'yml'
          - 'yaml'

  tasks:
    - name: "Include task for managing collections"
      when:
        - hub_collections is defined
        - hub_collections | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection

    - name: 'Include task for managing collection remotes'
      when:
        - hub_collection_remotes is defined
        - hub_collection_remotes | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_remote

    - name: 'Include task for managing collection repositories'
      when:
        - hub_collection_repositories is defined
        - hub_collection_repositories | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_repository

    - name: 'Include task for managing collection repository sync'
      when:
        - hub_collection_repositories is defined
        - hub_collection_repositories | length is not match('0')
        - item['wait'] is defined
      loop: "{{ hub_collection_repositories }}"
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_repository_sync

    - name: 'Include task for managing execution environment container images'
      when:
        - hub_ee_images is defined
        - hub_ee_images | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_ee_image

    - name: 'Include task for managing execution environment registries'
      when:
        - hub_ee_registries is defined
        - hub_ee_registries | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_ee_registry

    - name: 'Include task for indexing execution environment registries'
      when:
        - hub_ee_registries is defined
        - hub_ee_registries | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_ee_registry_index

    # Uncomment only if you want to sync all EE images from the remote registry
    # This could consume a lot of disk space for images that may not be frequently used
    # - name: 'Include task for syncing execution environment registries'
    #   when:
    #     - hub_ee_registries is defined
    #     - hub_ee_registries | length is not match('0')
    #   ansible.builtin.include_role:
    #     name: infra.aap_configuration.ee_registry_sync

    - name: 'Include task for managing execution environment repositories'
      when:
        - hub_ee_repositories is defined
        - hub_ee_repositories | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_ee_repository

    - name: 'Include task for syncing execution environment repositories'
      when:
        - hub_ee_repositories is defined
        - hub_ee_repositories | length is not match('0')
        - item['wait'] is defined
      loop: "{{ hub_ee_repositories }}"
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_ee_repository_sync

    - name: 'Include task for managing Automation Hub group Roles'
      when:
        - hub_roles is defined
        - hub_group_roles | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.group_roles

    - name: 'Include task for managing namespaces'
      when:
        - hub_namespaces is defined
        - hub_namespaces | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_namespace

    - name: 'Include task for publishing collections'
      when:
        - hub_collection_list is defined
        - hub_collection_list | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_publish

    - name: 'Include task for managing Automation Hub Roles'
      when:
        - hub_roles is defined
        - hub_roles | length is not match('0')
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_role
...
