---
- name: 'Sync collection repositories in Automation Hub'
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: "../hub_vars/"
        extensions:
          - 'yml'
          - 'yaml'

  tasks:
    - name: Refresh token (prevent from expiring)
      ansible.builtin.command:
        cmd: >-
          curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          -d grant_type=refresh_token -d client_id="cloud-services"
          -d refresh_token="{{ redhat_automationhub_token }}" --fail --silent --show-error --output /dev/null

    - name: Sync collection repositories
      when:
        - hub_collection_repositories is defined
        - hub_collection_repositories | length > 0
      vars:
        aap_hostname: "{{ ah_host }}"
        aap_username: "{{ ah_username }}"
        aap_password: "{{ ah_password }}"
        aap_validate_certs: false
      ansible.builtin.include_role:
        name: infra.aap_configuration.hub_collection_repository_sync
...
