---
- name: 'Sync collection repositories in Automation Hub'
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Sync collection repositories
      infra.ah_configuration.ah_repository_sync:
        name: "{{ item }}"
        wait: false
      loop:
        - 'community'
        - 'rh-certified'
        - 'validated'
...
